@node 每一刻都是崭新的
@unnumberedsec 就喜欢《旅行》

好像很多摇滚专辑都是这样，十来首歌里只有一首喜欢的，但是就这一首歌就足够让你花钱买下整张唱片。

最初听《旅行》好像是听别人的推荐。听过第一遍以后觉得歌词与曲调配合得很好，听着有一种轻松超然的感觉，而且在清凉之中带着一缕温暖的感觉。

后来去小五台连穿，有人带了 MP3 和外置音箱，一路都在放许巍的这张专辑。在这种条件下听《旅行》绝对会让你对这首歌上瘾。五月的小五台还是满山荒草，著名的金莲花还没有开，但是歌词里提到的阵阵晚风和松涛，青山白云，在这里都有最完美的体现。

从此以后听这首歌又有了更多的感受。这是一首能让你回想起郊外清新的冷空气和路途中别人给你的温暖的歌。在都市中奔忙的人，如果能静下心来听这首歌，也会得到一种别样的体验。
