@node Rainbow Six
@unnumberedsec 评非正规出版物《虹彩六号》

这个王永成自称作者也太不把千万战术游戏爱好者放在眼里了。1998 年，一个名为 Tom Clancy's Rainbow Six 的战术射击游戏出现在玩家眼前，虽然其画面和 AI 都不尽如人意，但它仍然凭借真实的设定和严密的系统吸引了为数众多的玩家，并且不断推出续作和资料片。

这个游戏的标题已经表明，它改编自 Tom Clancy 的同名小说。这部小说也是出版于 1998 年。作者 Tom Clancy 以军事小说和政治惊悚小说而闻名。他是 Baltimore Loyola's College 的英文专业毕业生，曾在马里兰州做过保险经纪人。1984 年他受一艘苏联护卫舰叛逃瑞典未遂的故事启发，写成了他的第一部军事惊险小说《追击红色十月》(The Hunt for Red October)，这也是他第一部以 Jack Ryan 为主角的小说。后来 Jack Ryan 系列的作品还有《爱国者游戏》(The Patriot's Game)，《燃眉追击》(Clear and Present Danger)，《恐惧的总和》(The Sum of All Fears)等等，这几部小说都获得了很大的市场成功，但评论家总说 Clancy 的小说文字不够流畅优美。其实，Clancy 是以小说详实的细节描写和对政治、军事现状的真实表现而取胜的。由于 Clancy 的小说冷战色彩浓重，对苏联和中国的刻画都有失偏颇，所以中国大陆并未引进过他的作品（不过 Rainbow Six 系列和 Splinter Cell 系列游戏已经由 Ubi Soft 代理发行）。

Rainbow Six 也算是 Jack Ryan 系列中的一部，不过主人公由 Jack Ryan 换成了他的得力干将 John Clark。剧情不算太复杂，无非是这个由联合国组织的秘密特种部队如何与恐怖分子、叛徒和幕后的黑手作战，但作者补充的大量政治、科技和经济背景会让读者不禁怀疑 “Rainbow” 是否真的存在──太像有那么一回事了。而且作者对恐怖分子、前 KGB 特工以及故事发生的场所很可能做过许多功课，独特的真实感是这部作品的魅力所在。

我是先玩过游戏才对原作产生了兴趣。阅读原作的时候，回想起游戏中的关卡，会有种特别的亲切感。不过没有玩过游戏的人如果读英文版，对于前面大段关于训练的内容以及对于阴谋的铺垫可能会觉得有些乏味。但从 Rainbow 的第一次外勤任务开始，这部小说就可以把人“抓住”。

在书店里也曾看到过这本书的中译本，但是署名这个人很可能甚至连译者都不是，所以我不打算为他掏腰包。网上大概还能找到这本书前 15 章的中文翻译，英文版 pdf 用 eDonkey/eMule 可以下载到，窃以为大家就不必买“王永成”窃取他人劳动成果的版本了。 
