@node 浪客剑心：追忆篇
@unnumberedsec 唯美的暴力与反思的暴力

自《浪客剑心》以后，已经很久没有看过日本的 anime，倒不是觉得《浪客剑心》到了一个不可企及的高度，只是的确没有心思花时间在其他漫画上。这个暑假又买了 TV 版的《浪客剑心》来看，94集，奇怪么？

先说感性认识吧。看过 Animatrix 附带的导演访谈以后，才注意到日本 anime 的特别之处──大量静止画面！《浪客》剧场版也不例外。很多画面都是只有雪代巴一张樱唇一开一合，或者静止的雪地背景上，花瓣缓缓落下……日本人确实很会偷懒，每周数百分钟的动画节目就是这样制作出来的。

但是，我不是要骂他们。这种效果是动感强烈的欧美动画片无法体现的。Anime 和 animation 确实是不同的东西。Anime 有些像舞台剧，有固定的背景，有活动的演员，如果演员不出场，用背景和音乐也可以衬托气氛。而 animation 就象电视或者电影，如果出现完全静止不动的画面，你多半会觉得你面前或身后的电器出了问题……

所以，anime 天生具有这样一种舞台剧一般的宁静气氛，至于你看到的热血或者是搞笑的 anime，是其他效果掩盖了这种宁静的结果。而《追忆篇》中需要的就是这种宁静，或者说这种风格正适合它的选材。无论是大战之前的肃杀，还是乡间生活的平淡，都因为这种静止的风格而显得很唯美，能给人极为深刻的印象。

此外，声优和画师的工作也很值得赞赏。绯村的配音凉风真世在这部剧场版动画里的声音冷而硬，跟 TV 版里动不动就搞笑地“O RO~”一声变成金鱼眼的形象完全不同，他们的专业水准果然是其他国家的配音演员都难以企及的。画风与 TV 版也有很大不同，更成人化、更冷峻一些，比较接近漫画原作。一些镜头，如剑心在风雪之中的跋涉，以及最后与斋藤一的对决，都是剧场版动画中堪称经典的场面。

嗯，然后是剧情。起先仍然是乱世之中的少年被武功高强的师父所救，然后学习剑术，用自己的剑追寻自己认为的正义道路这种老套故事。但是自可怜的清里被杀之后，整个片子其实都是在探讨为了建立新世界而毁灭旧世界的一切是否恰当这样的命题。抱着以剑救世的思想担任杀手工作的绯村，也就是在与清里交手后产生了动摇和怀疑吧。

而巴的出现和他们二人在乡下的避难生活是全剧最宁静而又最紧张的部分。在宁静的二人生活之外，是各种各样的阴谋，很有些树欲静而风不止的味道。“避世”的艰难让人觉得十分无奈。

最后的结局更是无奈，不过，也许正是这种无奈让绯村认识到了拔刀斋的名声带给自己的只有不得安宁的痛苦，他才走上了不同于志志雄的流浪之路吧。从这个角度说，救了绯村剑心的正是雪代巴啊。

如果能理解一个在战争中杀人如麻的人在某些情况下也会忏悔，而不把这种行为看做是伪善或掩饰的话，应该能理解《追忆篇》的含义。 
