@node Sin City
@unnumberedsec 孰之罪？

Sin, leaving the path set to man by God.

虽然是在12寸的笔记本显示器上看的此片，但是震撼丝毫不减。出国前一周内看了三遍，到国外还想再看，无奈国外原版 DVD 实在太贵。

震撼之处，倒不在于肯定下了一番工夫的高对比黑白效果，虽然这对增强震撼力肯定有一些作用。真正震撼的可能还是 Sin City 里形形色色的人物为了生存的挣扎，还有绝对邪恶的权威控制下这种挣扎的无奈。

陷害，背叛，无数的阴谋让这些小人物们付出了难以承受的代价。而这些却只是大人物们为了自己的一点私利，或者虚伪的名誉而布下的棋局。小人物们在这个城市里看不到正义，看不到希望，只能以狡猾、残忍和暴力作为谋生的工具，苟活于这个城市食物链的某一层级。

而为了生存，他们也必须接纳弱肉强食的法则，虽然对方可能跟自己一样也不过是在这个城市里努力求生存，但争斗的结果必然是一方的死亡，哪怕这个人可能还曾和自己有过一面之缘。我想这是最后一句台词 "everything could happen" 的一种解读。所以出场的所有角色中，除了 Hartigan 和 Nancy 以外，每个人都带着 sin。

但是这些人的 sin 在观众看来是可以接受的。因为他们的罪并非完全出于自愿，而是更大的 sin 让他们走上了复仇和杀戮的不归之路。真正的 sin 是 Roarkes 的不可饶恕的罪。

所以，当影片用我们能想到的最暴力的手段展现了 Kevin 和 Roarkes 的死，虽然正义并不存在，作为观众的我们还是感到了一种畅快，毕竟恶有恶报。虽然小人物们过着这样一种无奈而 lousy 的生活，可他们的反抗才使 Basin City 虽然充满罪恶，却并没有成为绝望之城。

从这个角度来说，这部电影有一种 desperado 的血性在其中，你不可以带着太厚的道德有色眼镜去评价它的血腥和暴力，那是一种现代人都有的对不公正的不快在宣泄。没有它们， Sin City 会是一部像 X-Man 一样的爆米花电影，观众和电影里面的人物都会郁闷不已。

至于 Hartigan 和 Nancy，他们是一种象征，作为没有带着 sin 的人，他们象征着 Marv、Gail 他们潜意识里追求的公正和善良，也可以说是这个黑暗都市里的一抹亮色。

过几天有机会，再看看大银幕上的 Sin City，看这一次它会不会给我带来新的感受。
