@node 历史研究（单卷本）
@unnumberedsec 挑战与应战

这本书是阿诺德·汤因比在完成他的12卷巨著《历史研究》后，根据读者的意见缩写的版本。我没有读过12卷版，但粗读了一遍这本书后，觉得即使只是这样一个缩写版本也体现了世界历史的脉络，而且基本阐释清楚了汤因比的挑战与应战理论。如果不是专业研究历史但对历史及史学感兴趣的读者，买这本书来看应该是很合适的。

书中汤因比的核心理论是挑战与应战理论。好久没有重温了，试着解释一下。历史中的每个事件都可以看做是一方发出挑战，另一方以某种方式应对的过程。例如农业对采集和捕猎方式的挑战，游牧社会对中央集权国家的挑战等等。如果应战一方成功，则它将以改变的面貌继续存在下去。而如果挑战一方成功，它将改变历史的面貌。挑战可以看做一种“革命”的力量，而应战则可看做一种保守的力量，但在挑战面前，应战往往也表现为某种改变。

全书从人类文明之初，一直到作者所处的现代，勾勒出人类文明的脉络，提出人类历史就是在挑战与应战的交错中不断前进的观点。这是一种宏大的历史观。不知道12卷本《历史研究》对这种历史观有怎样的具体解释。

这本书翻译版的文字非常清晰流畅，想必原版更不在其下，虽然篇幅不短，但读起来并无拖沓冗长之感。书中对中国史的叙述客观公允，实在难得。而且如果把这本书与《枪炮、钢铁与病菌》对照来读，更有一番乐趣。其他断代史书籍，与这本书一同阅读，也可让人受益不少。 
