@node Touching the Void
@unnumberedsec 抉择，以及登山的残酷与美

如果挂在你下方20米处的是你身受重伤的好友，包围你的是6000米高山上致命的暴风雪，你会为了自己的生命，甘愿承受背叛的罪名，割断连接你和朋友，连接生或死的绳索吗（而你的朋友要求你这样做）？

先不要忙着回答。这对任何人来说都是一个困难的选择，而对没有接触过登山运动的人来说，这种选择的逻辑可能都难以理解。

我原先以为 Touching the Void 会是一部很小众的电影，喜欢的人喜欢得要命，不喜欢的人看着就会睡着，不过没有想到的是这部英国的低成本电影确实吸引了很广泛的观众。也许这部电影的魅力，不在于安第斯山的风光，而在于电影的后半部分把这样一个残酷的抉择摆在每个观众面前。而且，这不是编剧的灵机一动，这是两个活生生的人曾经面临的抉择。

坦白说，这个抉择之后，电影便没有了太多传统的所谓剧情张力，不过是一场狼狈下撤的真实记录，但是这种真实也是许多同类电影都没有做到的。我们好像和主人公一样被太阳曝晒着，或者躲在雪洞里等待黎明到来，又或者一起承受着脱水的痛苦。这种真实也使我以为这部电影不会受到圈子以外的人的欢迎。但真实的残酷与美确实给了它非同一般的魅力。真实的登山就是这样，没有顶峰的欢喜雀跃，随时都有危险相伴，却有着它独特的魅力，值得登山者为它承受风险和艰难困苦。

这部电影的演员只有三个欧洲男人和一座山峰，没有插叙倒叙，没有铺垫呼应，就像岩石一样朴素。但它就像一次真正的登山那样，会告诉你什么是对生命的责任。 
