@node 2006-02-20
@unnumberedsec Change of dissertation topic

I have done a lot of work on the previous topic, so this change will bring me some loss. However, it is definitely better than realising everything does not make much sense at the very end of the project.

Invasive species is not quite an issue in PDNP, therefore I am going to deal with Sphagnum propagation. Many things I studied can still be used in this topic. Dr. Bonn from the moors for the future is quite positive on this new topic. However, I need to talk to her on Wednesday about details.
