@node 2006-04-04
@unnumberedsec Difficulties becoming manageable

Next Monday I will obtain data from Moors for the future partnership. Hopefully I can extract possible Sphagnum patches from the IR images. However, I haven't used the software (MapInfo) before, nor do I know how to use the data across several GIS platforms that I may use.

Only after I get DEM will I be able to simulate soil moisture using MODFLOW. A good news is that I found it possible to use DEM directly in MODFLOW. The article is on GRASS' homepage. I may need to contact the author to get details.

What made me worry is the safety and feasibility to validate Sphagnum patches in summer. Those patches may be far from any footpath. I need to ask Jack how to work safely on those bogs.
