@node 2006-03-16
@unnumberedsec Hacking Modflow

I am exploring the example data in the MODFLOW software package. The structure seems more clear now. You have a .nam file which specify the work space, all input and output files and what packages you use. Then you have a input file for each of the packages, containing parameters needed by the package. Output are written to the file(s) you specified.

The problem now seems to be that I need to know what flow scheme or pattern or type is it in the area concerned.
