@node 2006-03-09
@unnumberedsec From site visit

I found some points where sphagnums present. However, they may be too close for WhyWhere to generate a useful distribution map. The next step would be getting a coarse map of sphagnum distribution, then I can seek more data points. Considering the scale of the research, the datasets provided in WhyWhere may not be fine enough. Then I will need to establish scores using data from the points. These can only be done after I get data from Moors for the Future.

Possible simplication approaches: use presence and absence as binary site score, instead of a level system. Use hydrology model only, to predict sphagnum presence.
