@node 2006-03-14
@unnumberedsec Update

I talked with Jack today. The questions are basically answered. Jack says my dissertation topic is ``tricky'' -- interesting but can be complicated.

The presence of Sphagnum may be obtained from PDNP library in Bakewell. I have already contacted them to see if they have what I want. Jack also suggested that Roy or other people may have RS images of that area. This was confirmed by Roy in this afternoon. However I did not figure out the names he mentioned. I will check PDNP first, and see if I really need satellite images.

The condition of habitat is largely determined by water availability. Nutrient and soil condition (peat present or not) are also worthy considering. These three parameters should be enough. Climate data can also be obtained from PDNP.

The size of patch and water description can serve as indicators of sphagnum patches.
