@node 2006-06-14
@unnumeberedsec Frustrating convergence problem

I guess I am approaching the real cause of the problem.  Some cells in simulation have oscillating values.  That is to say the water head in these cells change rapidly during simulation.  

I tried to reduce oscillation by adjusting DAMP value in the PCG2 solver, but the problem still exists even when the DAMP is as low as 0.00001.  At the same time it also leads to imbalance of water budget.  

If I exclude the ``bad'' cells with large head change by marking them as inactive cells, other cells will also oscillate to a more staggering extent.

During simulations I noticed that most oscillating cells are in layer 1, 2, 10 and 11, where soils with different transmissivity meet.  Besides, cells on borders tend to oscillate.  

 I need to find some means to reduce the head change in cells.  Or change solvers to make the model converge.  If I cannot make this I will have to fall back to more simplified models.
