@node 2006-04-11
@unnumberedsec A new phase in research

Yesterday I obtained the data from Moors for the Future Partnership. The aerial photograph is even more useful than I expected. The sphagnum patches are quite apparent and distincted on the photos. With both visible and infrared channels it is relatively easy to identify sphagnum patches from other features and vegetations.

Another problem would be transforming DEM to a format recognisable by MODFLOW. This is purely a technical problem. The parameterisation of the model may take a lot of time.

I guess now I can talk to my supervisor about my dissertation idea and progress after Easter.
