@node 2006-03-13
@unnumberedsec More realistic model, but questions remain ...

The field trip and following discussion with my tutor have made my dissertation project more realistic now. The focus of the research now is on establishing initial state for the model. However, some questions must be answered to achieve this:

@itemize
@item Is it reliable to predict distribution using a few witnesses? If yes, how many cases are needed and do they need to follow certain pattern?
@item Is it reliable to establish distribution model using only hydrology and nutrient parameters? Can data from literature or site survey be used?
@item The coarse grain distribution of Sphagnum? (So I know where to look for them during fieldwork)
@item What shall I measure if I encounter Sphagnum colonies?
@item Do I need research on burnt areas?
@item Usage of MODFLOW model and justification;
@end itemize

Question 1-4 I will ask Jack for answers. The rest need more reading. 
