@node 2006-02-12
@unnumberedsec Progressing for dissertation

I spent a few hours reading a rather old book on Scots pine's ecology. Jack says it is the most authorative literature I can find. It does not matter how old it is. The mechanisms will not change in 50 years time.

I grabbed some useful information in this book, such as pine's interaction with Sphagnums and the influence of grazing and shrubs. Seems the last time I read it I did not read that carefully. These information also helps me think about the dissertation.

The validity of simulation can be examined by past data. I hope there are historical data available. Disturbances took place in this period also should be identified, at least the major ones.

On Monday I will call the research manager for Moors for the Future asking about data availability and fieldwork issues. Tuesday I think I will ask Jack about a preliminary field survey: what to look at.

There are a few good books on ecological modelling in the library. I did not have time today to read them all. I will check them out shortly. The literature review is progressing smoothly.
