@node 2006-03-24
@unnumberedsec Modflow: another issue

More reading on MODFLOW made me realise that this model is not quite visual, at least it is the case for the free software version. Theorically you can still define gullies, streams, rivers and lakes in your input file manually, but it would be exhausting and errors are inavoidable.

Therefore I have these choices:

1. Read articles on MODFLOW applications to see how they get around this problem when they deal with real-life situation;

2. Read articles on SMDR applications to see if it applies to my study (recharged by precipitation, elevation difference
