@node 2006-05-25
@unnumberedsec Choosing sampling points

I need a score of sampling points to verify the spectral signature of sphagnum patches.  My original idea is to extract all pixels on the image.  Then use sample function in Excel or similar software to draw out sample points.  The problem, however, is that I have a too large dataset with over 200,000 pixels in a single grid cell.  To assign x,y values to each of them in one cell will take over 10 hours, and I have 7 such cells....

Thus I will turn to quota sampling method now.  I will generate random coordinate pairs once at a time.  The randomisation is controlled to ensure the position of the point within the cell.  Then I will check if the coordinate pair corresponds to the image of sphagnum patch.  If not, generate another pair.  This is repeated untill I have enough points for field observation.
