@node 2006-02-26
@unnumberedsec Models, models ...

I just found some hydrological models that can be used to predict soil moisture from fewer parameters. As the research area is small enough, some parameters can be considered as uniform across the area. Therefore I only need climate and DEM.

Then the moisture together with stream water quality can predict habitat preference. This will be cross-examined with WhyWhere prediction and ground truths.

Then I have habitat scores and can use them in CAPS model.
