@node 2007-07-16
@unnumberedsec ifmslide ——一个似乎没什么人用的 LaTeX 演示宏包

今天在无聊的时候随便用 locate 命令看了一下自己的硬盘，发现 TeXlive 2005 里还有一个用于制作 slide 的宏包，叫做 ifmslide。这个东东似乎利用了 texpower、seminar 等多个宏包的功能，有一些它自己的特点，包括：

- 可以方便地定义背景图像；
- 可以自定义导航按钮的形状和位置；
- 可以方便地开关导航栏和定义导航栏位置；
- 用 pdf 格式时生成幻灯片，用 dvi 格式可以生成 handout ，基本不需要改动代码。

不过还不清楚对中文支持如何，也不清楚是否像 Beamer 那样支持 pgf 提供的绘图命令。另外一个缺点就是没有提供设计好的模板，不清楚做出来的幻灯片美观程度如何。
