@node 2007-06-15
@unnumberedsec 不许郁闷

>“主席，世界上啥子四情是最痛苦地哟？”

>“上自习。”

>“还有比上自习更痛苦地不得？”

>（烟）“天天上自习……”

在北京痛苦的找房过程终于结束。目前我寄居在某大学的防空洞改造的招待所里，冬暖夏凉，安静舒适，而且既没有手机信号也没有网线，适合隐居。

之前找的几个房，因为都拿不出靠谱的房产证，虽然居住方便一些，但终归是不放心。现在想来，虽然我对小岛上的房子有诸多的不满，但当时租房的过程毕竟比这次方便多了。

为了用手机与他人保持联络，就必须从招待所的地洞里钻出来。作为一个穷学生，钻出来也没有多的事可做，只有假装还是个本科生，然后跑到该大学的教学楼去上自习。除了8月份要再考一次雅思考试需要复习，其它大量的自习时间应当怎样度过呢？其实这段时间倒觉得上自习并不是一件难熬的事，天天上自习也没有什么，大概是没有什么考试压力的缘故吧。既然时间很多，那么决定好好复习一下吃饭必须的统计学知识，有空再复习一下微积分，然后看看能不能自学个数学分析或者离散数学啥的。
