@node 2009-01-16
@unnumberedsec 大尺度气候指标的适用性

在动植物生态研究中，人们常常用到气候指标来构建生态系统对气候变化响应的
模型，并且假设这些气候指标对不同地区的动植物生态具有普遍适用性。但发表
在 Global Change Biology 上的一篇文章通过对不同地区的雌鹿体重的比较，
发现在一个地区能解释大部分变化的气候指标在另一个地区就成了微不足道的变
量。气候因素起什么样的作用，还取决于当地的植被类型和土壤等因素。文章作
者们由此推断说，此前的许多研究中，将基于一个地区的观察或实验结果的理论
推广到在其它地区的同类型生态系统而得出的结论可能是不可靠的。为了对气候
变化在一个地区的影响进行完整的评估，需要弄清气候对生态系统作用的路径，
也需要有更完整的当地气候数据。
