@node 2009-01-14
@unnumberedsec 科学媒体的现在与未来

在中国的科普又一次引起了网民关注的时候，美国人也在思考类似的问题，不过
他们考虑的是科学媒体的去中心化和基层化。这篇 blog 里提到的一个问题是美
国许多本地级的报纸不再报道科学和环境类的内容，但在未来，相应级别的草根
媒体也许可以承担这个功能，用 blog、podcast 等形式报道与社区生活有关的
科学和环境消息。该 blog 还给出了旧金山湾区的一个实例。 作为最贴近一般
人生活的层面，由社区媒体承担唤醒环境意识的任务也许是个好办法。当然具体
操作起来，直接深入到社区层面可能会比较麻烦，特别是这种报道对选材和长期
投入的要求非常高。这在社区媒体和科学媒体都不发达的中国更是困难。但是如
果有志投身科普工作的人能够按地区联合起来组建网络上的 local hub，从北京、
上海这样的大城市和省一级地区逐渐向下普及，应该是一件有社会意义的事。
