@node 2020-05-28
@unnumberedsec In Capitalist China, the World Loses Touch with You

-----BEGIN PGP MESSAGE-----

hQIMA+XxlyqpcQVuAQ//Ukc0vNcihGmq3XbzNfRkyE2T/0gCi8RmZPqcpmOD2TO1
37+Q0AyOKKBfvB0wtsZez0VPHC2hYa3R0U9JWJ1Crhhwwrd3KJQv//l7mXXgbSUq
52MymDQ2pLSBw1Me8s+XHhKqqzHGDCdCSRaPgbyUqeUe111ZfIsL2mO38pexa07R
h25EgGp6qS1OlDTHBEXzkZrhsw6NaB3YyOLz4PnBBcVThoGKOXDaMKqbhAbwShmb
qBPMftt7O3DDg9Mmvgp286hHPdJFyjNp1SUNYQ8b3j2NraVHZm2qeGiSPmLzhH3w
VMWCpfzUC06UNql9co318vBe1u6gEl4bhOg3mb5Uoka5UW3KZmmXI2MqlglYC9iw
YLsoHberbvCJpJc6JNMPvXE89QSa4rhMItaSsmk2oa0sISjyY/oeGe1xJSEABHdT
IJaq6JVx2SuBMwXZNVuf0F8ckKhsgDTLyH5MvTml1lTlhRm+lylm8gfMqFKdMmzo
E7RStPbAK3VZjIuxu2MsgH6c4cazp2x3N2w//Z5nHuko5rqc7e3TEM7vPIpWhno+
b82CTGt1QyK6xD2XnWiDu9+Q4CBMRRWOmF48g65Tp+hxvhspewT8j9UZ79nFhpkI
da47uz0poEoKOwdJT0ZN9IAdnNSHA26gN3btYgv/8UONNb+ZtKVmo9tdwzM7sCfS
6gGxLityFKPBL/lJVsnz07Ebp1u4lRgcdKEBIb3XLdiBFADDw/Emm4PzGQfq/HiS
tztrDOoL1ouxs7HciJZaXVutBDgfq7M3MfboxOFq1iiKavn8yOeF1hSJe5VjfPbn
GEhrYwtAXeBYNZZIaus5xCgtJkJCK5uZVfga9/9MSZsCNYAFdLkIm2nmsg4i8hL9
qJHkMKDqaz0fEi1ZPi7mBTNz4kY4NMzrW4nfhBfPfuJHALotyS3xI2T154j8ruzR
xkMf86mdiDOXLW/4dZZs7LbiPLoDPcABvyEDoMTfmMkiMDf6ydP0Q/nBAzoUjGY0
TuBqlYHv+/XOA6UqO04gP0AWin3N0PW+MqkO6QjT2By52DfyvwfeN9OcDA3+rZLG
KMdpYPAlO8y4mcIO59JqPLNaD6wEm5SWwPR50xibamKxjZjI8b51U8y0f9hnvbPa
faGYZzysEDWv6dY1YNLGuKLhhZnuD45b/CVAwoCGoC1Dxgzmk/Tbori/tyBxFIMX
SwUKijn86QDGCkXyvRxWDGphXI/nJOT4ROvMZusQqPLTkHcutkLw/Byl+wWrhDi+
9eU3fg9WZEAcUQW8bN50xiz7hpPCqcvXdAjtiGHUUnGuezS66+QDaCn2y+VfTMcZ
s8QQzpIzKSqzZrHuLtjgJlzhEj4j3gsxGbCn1nWzTh30r9TIwIOkPqFvS2dxjmCo
8hb8yhhII808aup9+FgnVf0k9D8Y08R1q1QtlWiwBAjDxkeXRoe83LlG+21CPxo8
OeNy4oPG3hX/99Aal//OAXyhKePQpSEfI5+wZWSvn7Blwibgp3A6acaua9YnsMUS
nTINlgc1yZ7yorO7IxSWafDHAE8RXdu0u+ukmqAEDHgxms60RXuUa3kmU06HTa9S
gJpNV3iUaNDDQ6yQneVexMtpL3jGsbamvP57hPJPqk9dsIDVkoH7bAu8RE6bKJWt
BkLux2lu+qLCvaE/oHIr+tkiGdlqK2imFfBj+zJMpm+BTinvE8FjFwqcaVrkO+9U
iHlVBshXUqNq92EdnRX1HNIwui8f97y5uwy6zw1NI7JYV6M+lAW9LJcDbG+m8neX
W9P5mC5D6zbNvkmGz/KbreqRSI0WKR7BcFJQ8N+hWIqOnVo8V8E9PF6EPYH3DPcB
PAw/zyMq/Otf2S9nsf7G6RPiLfsul7i3to/ZTTJeU9Ag4gw9rlGu35Pb5jg0waH8
O8NX+u7HDBxA0vVcilOFZDJGPlbO39Xv/pEKdejjWp0bGVz6L8mAtj94LKPYigfp
9nO5qH1R3cIh/vPJkXxBgjfQMkxefBTmY3Oy+Bkh5B4HnwfmOIBnjODB+V5bWqZt
nX4sun6zBeUtYYQOF1PJy9stemi1VdHsGyLvUgXaKI9fNwDijJZSOIumD2gDh2Li
pt/wOcIDsXWGBsZrDAlX
=bCgW
-----END PGP MESSAGE-----
