@node 2020-05-28
@unnumberedsec （高中）毕业即死亡

最近常有这种感觉，就是我在高中毕业时已经走上了个人人生的巅峰然后死去，后面 20 年都不过是延续着死亡那一瞬间的状态。

因为在那个瞬间之前，人生有个无比明确的目标。因为有这个目标的存在，别人和自己都忘了问“你长大了想干什么？”

之后的 20 年是什么状态呢，就是不断告诉自己生活的目标不是那么容易找到的，迷茫都是暂时的，自己一定会有灿烂发光的那一天。

然后就到了不得不面对现实的年纪。

一个从来都疲于应付其他人的期许和要求的人，怎么会仅仅因为愿望，就知道自己该干什么和可以干什么呢。

又怎么会比那些知道自己的愿望和方向的人做得更好呢。

当然重来也不会好过现在。但是我现在不想再度奋起。就接受被别人安排的命运好了。
